Add Websocket OAuth2 Documentation
bnc-projects/web-api pull request #11
Opened 2018-10-01 03:59 UTC by pushkar-g

2018-10-01 04:25 UTC, alphafoobar requested changes
Looks great - but I needed to change the websocket URL to connect. Cheers!

2018-10-01 04:25 UTC, alphafoobar commented on openapi.yaml
> +      ``wss://ws.bravenewcoin.com/access_token=``
URL format should be?
``wss://ws.bravenewcoin.com?access_token=``

2018-10-01 23:14 UTC, alphafoobar approved these changes

2018-10-02 22:48 UTC, bhavikkumar approved these changes
I updated the asset schema

2018-10-02 22:49 UTC, merged